spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/demo?useSSL=true
    name: demo
    username: sa
    password:
logging:
  level:
    jdbc.sqlonly: DEBUG
    jdbc.sqltiming: INFO
    jdbc.audit: INFO
    jdbc.resultset: ERROR
    jdbc.resultsettable: DEBUG
    jdbc.connection: DEBUG
