spring:
  profiles:
    active: @maven.spring.profile@
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    name: demo
    username: sa
    password:
